# Generated by Django 2.2.5 on 2020-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(choices=[('MED', 'MEDICAL'), ('ELE', 'ELECTRO-MECHANICAL'), ('FUN', 'FURNITURE')], max_length=5, verbose_name='category')),
                ('acquired_on', models.DateField(verbose_name='Equipment Registration Date')),
                ('functional_status', models.CharField(choices=[('GD', 'GOOD WORKING CONDITION'), ('SER', 'DUE FOR SERVICE'), ('DOWN', 'UNREPAIRABLE')], default='GD', max_length=6)),
                ('service_interval', models.PositiveIntegerField(blank=True, help_text='Service Interval in days for machine that requires service', null=True, verbose_name='Service Interval')),
                ('last_service_date', models.DateField(blank=True, help_text='Last Service date for serviceable machine', null=True, verbose_name='Last Service Date')),
            ],
            options={
                'verbose_name_plural': 'Fixed Asset Register',
            },
        ),
    ]
