# Generated by Django 2.2.5 on 2020-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DR', 'Drug'), ('LTK', 'Lab Test Kit'), ('CON', 'Consultation Fee')], max_length=5),
        ),
    ]
