# Generated by Django 2.2.5 on 2020-06-17 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('dob', models.CharField(blank=True, help_text='Please enter date of birth in format:dd/mm/yy', max_length=30, null=True, verbose_name='Date of Birth')),
                ('age', models.PositiveSmallIntegerField(default=1, verbose_name='Age')),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IN', 'INPATIENT'), ('OUT', 'OUTPATIENT')], max_length=4, verbose_name='Visit Type')),
                ('clinical_notes', models.TextField(help_text='Examination and Diagnosis Carried Out')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='Visit Date')),
                ('lab_tests', models.TextField(blank=True, verbose_name='Lab Tests Taken')),
                ('prescriptions', models.TextField(blank=True, verbose_name='Prescriptions Required')),
                ('attendant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visits_handled', to=settings.AUTH_USER_MODEL, verbose_name='Medical Personel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='clinic.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': 'Clinic Visits',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternate Phone')),
                ('designation', models.CharField(choices=[('DR', 'Doctor'), ('NR', 'Nurse'), ('LT', 'Laboratory Technician'), ('RR', 'Receptionist')], max_length=2, verbose_name='Designation')),
                ('employee_photo', models.ImageField(blank=True, default='employee_images/placeholder.png', upload_to='employee_images/')),
                ('is_mvp', models.BooleanField(default=False, help_text='is employee of month')),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
