# Generated by Django 2.1.4 on 2019-03-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(auto_now_add=True, verbose_name='Visit Date'),
        ),
    ]
