# Generated by Django 2.2.5 on 2020-06-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_handled', to=settings.AUTH_USER_MODEL, verbose_name='Medical Personel'),
        ),
    ]
