# Generated by Django 2.2.4 on 2019-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, default='employee_images/placeholder.png', upload_to='employee_images/'),
        ),
    ]
