# Generated by Django 2.2.5 on 2020-05-14 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190908_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='attendant',
            field=models.ForeignKey(default='Unknown Employee', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visits_handled', to=settings.AUTH_USER_MODEL, verbose_name='Medical Personel'),
        ),
    ]
