# Generated by Django 2.2.5 on 2020-06-17 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20200616_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='attendant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visits_handled', to=settings.AUTH_USER_MODEL, verbose_name='Medical Personel'),
        ),
    ]
