# Generated by Django 2.1.4 on 2019-01-17 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'product_category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.PositiveSmallIntegerField(choices=[(0, 'Fully Paid'), (1, 'Partially Paid'), (2, 'Not Paid')], default=2, editable=False)),
                ('customer', models.CharField(default='Cash Payment', help_text='Enter Customer name to keep track of debtors', max_length=100)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid')),
                ('employee', models.ForeignKey(default='Clinic Attendant', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Quantity sold', verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'Order Item Particulars',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retail Price')),
                ('description', models.TextField(blank=True, help_text='Product Description')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Available Stock')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.Category', verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternate Phone Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.Product', verbose_name='Product Name'),
        ),
    ]
