# Generated by Django 2.1.4 on 2019-01-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('clear_debt', models.BooleanField(default=False)),
                ('debt_amount', models.PositiveIntegerField(default=0, editable=False, verbose_name='Debt Amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
            ],
            options={
                'verbose_name_plural': 'Debtors',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date Purchased')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity Purchased')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Product')),
                ('supplier', models.ForeignKey(default='Unknown Supplier', on_delete=django.db.models.deletion.SET_DEFAULT, to='sales.Supplier')),
            ],
        ),
    ]
