# Generated by Django 2.1.4 on 2019-03-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_debtor_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Debt Amount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(default='Unknown Supplier', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items_supplied', to='sales.Supplier'),
        ),
    ]
