# Generated by Django 2.1.4 on 2019-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190303_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Mark as Fully Paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Debtor',
        ),
    ]
